### PR TITLE
Fix incorrectly wrapped strings by localization routines

### LINKED ISSUE #413: sqlcmd prints incorrectly strings
The latest build prints erroneous strings.
```
>.\sqlcmd.exe stop
Stopping %!!(string=mcr.microsoft.com/mssql/server:latest)q(BADINDEX) for context %!!(string=mssql)q(BADINDEX)
```

### PR DESCRIPTION
**Pull request by apoorvdeshmukh**
Fixes #413 

```
git\go-sqlcmd>.\sqlcmd.exe start
Starting "mcr.microsoft.com/mssql/server:latest" for context "mssql"

git\go-sqlcmd>.\sqlcmd.exe stop
Stopping "mcr.microsoft.com/mssql/server:latest" for context "mssql"

git\go-sqlcmd>.\sqlcmd.exe remove --force --yes
Removing context mssql
Container "4909e2af7b209c3dd395911747882d90a90ee43ed7ed0ea335fdeb96481abd29" no longer exists, continuing to remove context...
Operation completed successfully
```

### CODE REVIEW

File: cmd/modern/root/uninstall.go [hunk 1]
```diff
@@ -116,10 +116,7 @@ func (c *Uninstall) run() {
 			output.Infof(localizer.Sprintf("Removing context %s", config.CurrentContextName()))
 
 			if controller.ContainerExists(id) {
-				output.Infof(
-					"Stopping %s",
-					endpoint.ContainerDetails.Image,
-				)
+				output.Infof(localizer.Sprintf("Stopping %s", endpoint.ContainerDetails.Image))
```
Comment (shueybubbles) [inline cmd/modern/root/uninstall.go:119]: >of [](http://example.com/codeflow?start=14&length=2)

what happens if endpoint.ContainerDetails.Image contains a combination that also happens to be a Go format specifier? Won't that cause output.Infof to treat it as a format string?

```go
sub := "%d"
m := localizer.Sprintf("something %s", sub)
output.Infof(m)
```

Comment (shueybubbles) [reply cmd/modern/root/uninstall.go:119]: Go libraries typically have 2 versions of string functions - one with "f" and one without. Does `output` have `Info` and `Warn` functions ? If we aren't passing a format string we shouldn't be using and `f` function.

**Review by shueybubbles — CHANGES_REQUESTED** [review]
:clock1:

File: cmd/modern/root/uninstall.go (hunk 1 above)
Comment (apoorvdeshmukh) [reply cmd/modern/root/uninstall.go:119]: Yes. It could be an issue if sub contains format specifier. We have added these functions under output package. I'll add the non `f` variants `output.Info` and `output.Warn` and use them.

File: internal/output/output.go [hunk 2]
```diff
@@ -223,3 +244,9 @@ func (o Output) printf(format string, a ...any) {
 	_, err := o.standardWriteCloser.Write([]byte(text))
 	o.errorCallback(err)
```
Comment (shueybubbles) [inline internal/output/output.go:245]: printf should probably just call print(text)

**Comment by shueybubbles** [comment]
> func (o Output) Errorf(format string, a ...any) {

can you update the linter to look for calls to Output functions that could lead to this bug in the future?
Today the linter doesn't block the build but at least someone running build\build locally could see the violation.

---
Refers to: internal/output/output.go:36 in 567c8e9. [](commit_id = 567c8e954c951be3625d6a325eb8a8f41dbd6928, deletion_comment = False)

File: cmd/modern/root/install/mssql-base.go [hunk 3]
```diff
@@ -603,7 +603,7 @@ func (c *MssqlBase) downloadImage(
 	output *output.Output,
 	controller *container.Controller,
 ) {
-	output.Infof(localizer.Sprintf("Downloading %v", imageName))
+	output.Info(localizer.Sprintf("Downloading %v", imageName))
 	err := controller.EnsureImage(imageName)
 	if err != nil || c.unitTesting {
 		output.FatalfErrorWithHints(
```
Comment (shueybubbles) [inline cmd/modern/root/install/mssql-base.go:609]: >.FatalfErrorWithHints [](http://example.com/codeflow?start=8&length=21)

this call looks problematic as well

**Comment by shueybubbles** [comment]
> 		output.FatalfWithHints(

this call is fine because there are no user-provided arguments, but please check other callers of these Fatalf methods.

---
Refers to: cmd/modern/root/install/mssql-base.go:627 in 567c8e9. [](commit_id = 567c8e954c951be3625d6a325eb8a8f41dbd6928, deletion_comment = False)

File: internal/output/output.go (hunk 2 above)
Comment (apoorvdeshmukh) [reply internal/output/output.go]: Fixed

**Comment by apoorvdeshmukh** [comment]
> > func (o Output) Errorf(format string, a ...any) {
> 
> can you update the linter to look for calls to Output functions that could lead to this bug in the future? Today the linter doesn't block the build but at least someone running build\build locally could see the violation.
> 
> Refers to: internal/output/output.go:36 in [567c8e9](https://github.com/microsoft/go-sqlcmd/commit/567c8e954c951be3625d6a325eb8a8f41dbd6928). [](commit_id = [567c8e9](https://github.com/microsoft/go-sqlcmd/commit/567c8e954c951be3625d6a325eb8a8f41dbd6928), deletion_comment = False)

I'll take this as a follow up item. Since we are using localization routines in all of these functions (except few places) , I have added the non f variants of the existing print functions and have replaced it everywhere.

File: cmd/modern/root/install/mssql-base.go (hunk 3 above)
Comment (apoorvdeshmukh) [reply cmd/modern/root/install/mssql-base.go]: Yes. Replaced the call with `FatalErrorWithHints`

**Comment by apoorvdeshmukh** [comment]
> 

There were similar issues with other `f` functions too. Fixed them.

**Comment by apoorvdeshmukh** [comment]
> > ```
> >   output.FatalfWithHints(
> > ```
> 
> this call is fine because there are no user-provided arguments, but please check other callers of these Fatalf methods.
> 
> Refers to: cmd/modern/root/install/mssql-base.go:627 in [567c8e9](https://github.com/microsoft/go-sqlcmd/commit/567c8e954c951be3625d6a325eb8a8f41dbd6928). [](commit_id = [567c8e9](https://github.com/microsoft/go-sqlcmd/commit/567c8e954c951be3625d6a325eb8a8f41dbd6928), deletion_comment = False)

There were similar issues with other `f` functions too. Fixed them.

**Review by shueybubbles — APPROVED** [review]
:shipit:
