### PR TITLE
Fix rendering of dynamic time values

### LINKED ISSUE #77: The presentation of date/time data types needs some polishing
I would guess this is on a to-do-list, but I file it never the less.

The presentation of datetime values is a little funny as demonstrated by the screenshot below.

- For datetime, +00 is added if the fraction is 0.
- For datetime, no trailing zero is printed when last digit in fraction is 0.
- For date, hours and minutes are printed.
- For datetime2 a +0000 UTC is added that should not be there.
- For datetime2(3) .000 is not printed.
- For time a date of 0000-01-01 is added. Likewise a time zone which should be there is added.

image

### PR DESCRIPTION
**Pull request by shueybubbles**
Fixes #77 
I had to make a driver change first, so now go-sqlcmd will consume `microsoft/go-mssqldb`

### CODE REVIEW

File: pkg/sqlcmd/format.go [hunk 1]
```diff
@@ -451,7 +461,26 @@ func (f *sqlCmdFormatterType) scanRow(rows *sql.Rows) ([]string, error) {
 				row[n] = x
 			case time.Time:
 				// Go lacks any way to get the user's preferred time format or even the system default
```
Comment (kenvanhyning) [inline pkg/sqlcmd/format.go:463]: If I am reading this correctly, there is now a way to get the format string, yes?  Can we strike this comment now?

**Review by kenvanhyning — APPROVED** [review]

File: pkg/sqlcmd/format.go (hunk 1 above)
Comment (shueybubbles) [reply pkg/sqlcmd/format.go:463]: No, I simply used the same format SQL server uses by default, modified by the precision value for the number of decimal places.
I opened #80 to discuss ways to allow user-provided format strings.
