### PR TITLE
fix -h switch

### LINKED ISSUE #67: sqlcmd -? does not work and -h does the wrong thing.
If I run `sqlcmd -?` with the established SQLCMD I get a list of option. If I run this with go-sqlcmd, I get:

sqlcmd: error: unknown flag -?, did you mean one of "-h", "-c", "-C", "-d", "-E", "-U", "-i", "-o", "-q", "-Q", "-S", "-X", "-G", "-x", "-v", "-a", "-l", "-H", "-K", "-N", "-b", "-V", "-m", "-F", "-r"?

`sqlcmd -h` or `sqlcmd --help` gives the desired result. However, `-h` has an established meaning with SQLCMD to specify how often you want headers printed. I would guess that there quite a few bat files out there with `SQLCMD -h-1` in them. These are people who use SQLCMD to export data and the argument -1 suppresses the headers entirely.

`--help` can still be used for help, but it is not a good idea to use `-h`.

### PR DESCRIPTION
**Pull request by shueybubbles**
Fixes #67 
thx to @stuartpa for blazing the trail

### CODE REVIEW

File: cmd/sqlcmd/main.go [hunk 1]
```diff
@@ -49,14 +49,18 @@ type SQLCmdArguments struct {
...
 }
 
 // Validate accounts for settings not described by Kong attributes
 func (a *SQLCmdArguments) Validate() error {
 	if a.PacketSize != 0 && (a.PacketSize < 512 || a.PacketSize > 32767) {
 		return fmt.Errorf(`'-a %d': Packet size has to be a number between 512 and 32767.`, a.PacketSize)
 	}
-
+	if a.Headers < -1 {
+		return fmt.Errorf(`'-h %d': header value must be either -1 or a value between -1 and 2147483647`, a.Headers)
```
Comment (stuartpa) [inline cmd/sqlcmd/main.go:62]: Should this be:

header value must be either -1 or a value between **0** and 2147483647

File: cmd/sqlcmd/main.go [hunk 2]
```diff
@@ -49,14 +49,18 @@ type SQLCmdArguments struct {
 	ErrorLevel                  int               `short:"m" help:"Controls which error messages are sent to stdout. Messages that have severity level greater than or equal to this level are sent."`
 	Format                      string            `short:"F" help:"Specifies the formatting for results." default:"horiz" enum:"horiz,horizontal,vert,vertical"`
 	ErrorsToStderr              int               `short:"r" help:"Redirects the error message output to the screen (stderr). A value of 0 means messages with severity >= 11 will b redirected. A value of 1 means all error message output including PRINT is redirected." enum:"-1,0,1" default:"-1"`
+	Help                        bool              `short:"?" help:"show syntax summary"`
```
Comment (stuartpa) [inline cmd/sqlcmd/main.go:52]: end with '.'?

**Review by stuartpa — APPROVED** [review]

**Review by dzsquared — APPROVED** [review]

File: cmd/sqlcmd/main.go (hunk 1 above)
Comment (shueybubbles) [reply cmd/sqlcmd/main.go:62]: 0 is invalid too. I copy/pasted the error from the original sqlcmd and it's wrong there
```
e:\>sqlcmd -h 0
Sqlcmd: '-h 0': header value must be either -1 or a value between -1 and 2147483647
```

I'll use 1
